In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr.shape

(5,)

In [9]:
arr[0]

1

In [11]:
arr[3:]

array([4, 5])

In [12]:
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [16]:
print("2nd element of 1st row: ",arr2[0,1])

2nd element of 1st row:  2


In [17]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [18]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4,3)

In [20]:
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
for x in newarr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10
11
12


In [23]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [24]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [25]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [26]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
